### ISSUE TITLE
[Task] Add data-attributes

### ISSUE THREAD

**Issue by Elizaveta1105** [rocket-admin/rocketadmin#334]
P.S: For all test connections test-ids should be added as shown here (whole list, every table item, widgets)

![Image](https://github.com/rocket-admin/rocketadmin/assets/64523120/8ff4491c-1b18-40e5-9394-d5c9aec8e5af)

Alerts. 
there are 3 alerts which front end might throw:
1. `data-test-id="alert-not-configured"` when Settings or Widgets are not setup;
2.` data-test-id="alert-no-primary-keys"` when table doesn't have primary keys;
3. `data-test-id="alert-widgets-warning"` when something wrong with widgets.
and 1 alert for errors from server:
`data-test-id="alert-server-error"`

List of tables — `data-test-id="tables-list"`, each item — `data-test-id="table-{{tableName}}-list-item"`, 

![Image](https://github.com/rocket-admin/rocketadmin/assets/64523120/88b0190f-7e79-4911-ab8a-895353cd99bc)
![Image](https://github.com/rocket-admin/rocketadmin/assets/64523120/357e1d0f-a072-47d4-860f-f7d5f5c1927c)

`data-test-id="login-header-link"`, `data-test-id="registration-header-link"`
`data-test-id="login-email-input"`
`data-test-id="login-password-input"`
`data-test-id="forgot-password-link"`
`data-test-id="login-button"`
`data-test-id="login-google-button"`

![Image](https://github.com/rocket-admin/rocketadmin/assets/64523120/be682192-8914-4e3b-8813-544dd620d8be)

right now Upgrade button might work in 2 scenarios:
`data-test-id="upgrade-stripe-link"` — if user have already subscribed, it redirects them directly to Stripe account;
`data-test-id="upgrade-local-link"` — if user whats to subscribe for the first time, it redirects then on our page with plans.
But we are going to change it and make switching between plans from our pages. So maybe it's better to postpone to test this payment thing. 

`data-test-id="logout-button"`
`data-test-id="add-connection-button"`
`data-test-id="{{connectionId}}-test-connection-list-item"`

![Image](https://github.com/rocket-admin/rocketadmin/assets/64523120/2aa89378-e3c4-4a12-98c4-4c5e676b6f6b)

`data-test-id="dashboard-tab"`, `data-test-id="audit-tab"`,  `data-test-id="users-tab"`, `data-test-id="edit-db-tab"`, `data-test-id="connection-settings-tab"`

![Image](https://github.com/rocket-admin/rocketadmin/assets/64523120/6a5f5140-e4e3-45f3-a11a-166ebc951a3c)

`data-test-id="connections-list-header-link"`, `data-test-id="account-header-link"`

![Image](https://github.com/rocket-admin/rocketadmin/assets/64523120/e5413767-2219-44b2-a2ca-e6b417355c93)

`data-test-id="user-name-input"`, `data-test-id="save-user-name-button"`,
`data-test-id="change-user-email-button"`,
`data-test-id="change-user-password-link"`.

**Comment by lyubov-voloshko** [comment]
<img width="1440" alt="image" src="https://github.com/rocket-admin/rocketadmin/assets/22369784/8a5aca59-72b7-456e-8108-278d6ff1afb6">

`data-test-id="login-header-link"`, `data-test-id="registration-header-link"`
