### ISSUE TITLE
Table records for Postgres test connection are doubled

### ISSUE THREAD

**Issue by Elizaveta1105** [rocket-admin/rocketadmin#335]
1. Login with test_account@test.com / Test123456
2. Open Postgres test connection https://app.rocketadmin.com/dashboard/93b5f51b-2bdc-4fcf-bec0-9dcdb90ccd92/actor

Actual result: table records are repeated
Expected: single table records

![Image](https://github.com/rocket-admin/rocketadmin/assets/64523120/df7cf5d3-ca7b-4339-b86e-688c11ff6e19)

**Comment by Artuomka** [comment]
fixed
