### ISSUE TITLE
I can't run the project in my localhost

### ISSUE THREAD

**Issue by sleeviin** [rocket-admin/rocketadmin#398]
I am trying to run the project, but after finally getting running I just see what I assume it's the nest backend project:

![image](https://github.com/rocket-admin/rocketadmin/assets/3312062/76b526c5-417a-48f3-9118-c7d2a3529f51)

Steps to reproduce:
have docker already installed and running

run the next command:

docker run -d \
  -e DATABASE_URL=postgresql://username:password@host/database \
  -e JWT_SECRET=<jwt_secret> \
  -e PRIVATE_KEY=<private_key> \
  -e TEMPORARY_JWT_SECRET=<temporary_jwt_secret> \
  -e APP_DOMAIN_ADDRESS=http://localhost:3000 \
  -p 3000:3000 \
  --name rocketadmin \
  rocketadmin/rocketadmin
  
  then in docker you will see the next image:
  
![image](https://github.com/rocket-admin/rocketadmin/assets/3312062/cfe66675-fdc8-4ad0-b9de-1b36bae22c94)

What I am missing? I need help, thanks!

**Comment by gugu** [comment]
Hi! You need to expose port 8080 instead of 3000

**Comment by sleeviin** [comment]
If I use port 8080 it doesn't load at all, how I can expose that port?

**Comment by saturn4er** [comment]
Just got same error. @sleeviin try to use 8080:80
